---
abstract: 'Ark plugins for Reproxy'
author:
  - 'Daisuke Murase <typester@cpan.org>'
build_requires:
  Test::More: 0.98
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.9.0, CPAN::Meta::Converter version 2.131560'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Ark-Plugin-ReproxyCallback
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - builder
provides:
  Ark::Plugin::ReproxyCallback:
    file: lib/Ark/Plugin/ReproxyCallback.pm
    version: 0.01
  Ark::Plugin::ReproxyCallback::OpenSocial:
    file: lib/Ark/Plugin/ReproxyCallback/OpenSocial.pm
requires:
  perl: 5.008001
resources:
  bugtracker: https://github.com/ark-framework/Ark-Plugin-ReproxyCallback/issues
  homepage: https://github.com/ark-framework/Ark-Plugin-ReproxyCallback
  repository: git://github.com/ark-framework/Ark-Plugin-ReproxyCallback.git
version: 0.01
x_contributors:
  - 'Songmu <y.songmu@gmail.com>'
